### ISSUE TITLE
Sample State and Routes 

### ISSUE THREAD

**Issue by PLUCS2** [syldysnya/OpenDnDTable#3]
## State
- [x] What is currentReservationId in the sessions slice of state? 

## Backend 
- [x] How will points be added to the current user? 

## Frontend 
- [x] You will want different routes for rendering previous reservations (and upcoming), etc. (things currently listed under the `/players/:players_id` 

Excellent work! Let me know if you have any questions!

**Comment by syldysnya** [comment]
>What is currentReservationId in the sessions slice of state?
Yeah, I think I understood this part wrong in the beginning when I was doing it.  First I thought that I need it because my current logged in user will have (or not) current reservation and this info is important for sessions (for not reserving the same game place, on the same time and day). But after studying and practicing more It kinda doesn't make sense anymore. This information will store in players' props, so I don't really need to keep it in sessions. I deleted this part in sessions.

>How will points be added to the current user?
When a user will be making a reservation, them will have a check-in box to add 100 points. If they agree, it will be added. If they'll cancel a reservation they got points for, points will be decreased by 100. I added a joint table to my schema, called reservations_points. It will keep a track of points and reservations, so if a reservation is destroyed then the total number of points will also decrease by 100 from a current user's total points.

>You will want different routes for rendering previous reservations (and upcoming), etc. (things currently listed under the /players/:players_id
I can't understand this part completely but I changed it. From my understanding user will have a list of current and past reservations. To view a reservation or to edit it, or to check an old reservation, a user will have to go to another page (/book/:reservationId), so I made a new path(route) for it. Should I still keep reservationsIndex under /players/:playerId?
